name: Push-to-EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main

        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - uses: actions/checkout@v2
      - name: Python Linter
        uses: sunnysid3up/python-linter@master
        with:
          source: "./social_news"
          mypy-options: "--ignore-missing-imports --show-error-codes"
          pylint-options: "--rcfile=setup.cfg"
          isort-options: "-w 100"
          django: true
